//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prakt17_praktika1_
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeCash
    {
        public int Id { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string SecondName { get; set; }
        public string PodrazdName { get; set; }
        public System.DateTime DateWork { get; set; }
        public int CashSumm { get; set; }
        public int Experience { get; set; }
        public int Category { get; set; }
        public string Post { get; set; }
    }
}
