//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prakt17_praktika1_
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WorkerCashEntities2 : DbContext
    {
        public WorkerCashEntities2()
            : base("name=WorkerCashEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EmployeeCash> EmployeeCashes { get; set; }

        private static WorkerCashEntities2 context;

        public static WorkerCashEntities2 GetContext()
        {
            if (context == null)
                context = new WorkerCashEntities2();
            return context;
        }
    }
}
