//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prakt17_praktika1_
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WorkerCashEntities3 : DbContext
    {
        public WorkerCashEntities3()
            : base("name=WorkerCashEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EmployeeCash> EmployeeCashes { get; set; }

        private static WorkerCashEntities3 context;

        public static WorkerCashEntities3 GetContext()
        {
            if (context == null)
            {
                context = new WorkerCashEntities3();
            }
            return context;
        }
    }
}
